In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Aim is to predict the marks of students of the test data

In [2]:
# Use the file namd 'training data' to train the model

data = pd.read_excel("Training data.xlsx")

x_train = np.array(data.iloc[:,0:8])
y_train = np.array(data.iloc[:,8]).reshape(-1,1)

'''for i in data:
  plt.plot(np.array(data[i]),y_train,'o')
  plt.xlabel(i)
  plt.ylabel('Marks')
  plt.show()'''


# Try plotting y_train with different features

# To get an idea whether to add some features or not
# Add some features if required in x_train

# Also do label encoding for features not represented in numbers
# refer the link if not know : https://youtu.be/589nCGeWG1w?si=t2Wa7LgbUOO4RooM

def feature_changing(x_train):
  # ---------
    # Your code here
  x_train[x_train == 'yes'] = 1
  x_train[x_train == 'no'] = 0
  x_train[x_train == 'M'] = 0
  x_train[x_train == 'F'] = 1
  # ---------
  return x_train

x_train = feature_changing(x_train)

print(x_train)


[[0 0 2 ... 6 18 118]
 [1 0 2 ... 7 19 107]
 [1 0 3 ... 5 18 108]
 ...
 [1 0 2 ... 5 17 123]
 [1 1 1 ... 8 17 104]
 [1 0 1 ... 6 18 128]]


In [3]:
def z_score(x_train):

  # ---------
    # write the code for feature scaling here
    # Your code here
  # ---------
  x_mean = np.zeros(x_train.shape[1])
  x_std = np.zeros(x_train.shape[1])
  x_square = np.zeros(x_train.shape[1])

  for i in range(x_train.shape[0]):
    x_mean = np.add(x_train[i],x_mean)
    x_square = np.add(x_train[i] ** 2 ,x_square)

  x_mean = (x_mean)/x_train.shape[0]
  x_square = (x_square)/x_train.shape[0]

  x_mean = x_mean.astype(np.float64)
  x_square = x_square.astype(np.float64)

  x_std = np.sqrt(x_square -(x_mean ** 2))

  x_train = (x_train - x_mean)/x_std


  return x_train,x_std,x_mean
z_score(x_train)

(array([[-1.464463754433791, -0.8562139061198019, 0.2867665212851301, ...,
         0.37590695876132685, 0.0331807384853717, 0.7714015047477445],
        [0.6828438033870168, -0.8562139061198019, 0.2867665212851301, ...,
         0.7514383860953195, 1.613215904455393, -0.17415416186972663],
        [0.6828438033870168, -0.8562139061198019, 1.3982646658011382, ...,
         0.00037553142733411814, 0.0331807384853717, -0.08819455581359288],
        ...,
        [0.6828438033870168, -0.8562139061198019, 0.2867665212851301, ...,
         0.00037553142733411814, -1.5468544274846496, 1.201199535028413],
        [0.6828438033870168, 1.1679324440452143, -0.824731623230878, ...,
         1.1269698134293122, -1.5468544274846496, -0.4320329800381278],
        [0.6828438033870168, -0.8562139061198019, -0.824731623230878, ...,
         0.37590695876132685, 0.0331807384853717, 1.6309975653090818]],
       dtype=object),
 array([ 0.46569947,  0.49403542,  0.89968661,  0.92281959,  1.26827402,
       

In [4]:
def cost(x_train,y_train,w,b):

  # ---------
    # Your code here
    # Use mean square error as cost function
    # return cost
  # ---------

  loss = 0
  for i in range(x_train.shape[0]):
    pred = np.dot(x_train[i].reshape((1,8)),w) + b
   
    loss += ((pred[0] - y_train[i])**2)

  loss = loss/(2.0* x_train.shape[0])
  
  return loss




In [5]:
def gradient_descent(x_train,y_train,w,b):

  # ---------
    # Your code here
    # Choose learning rate yourself
  # ---------
  alpha = 0.03
  m, n = x_train.shape
  
  dj_db = 0
  dj_dw = np.zeros(x_train.shape[1],np.float64)

  for  i in range(m):
    pred  = np.dot(x_train[i].reshape(1,n),w) + b
    error = pred[0,0] - y_train[i]
    dj_db += error

    for j in range(x_train.shape[1]):
      dj_dw[j] += error*x_train[i,j]

  dj_db /= (m)
  dj_dw /= (m)
  w = w- ((alpha*(dj_dw)).reshape(x_train.shape[1],1))
  b = b- alpha*(dj_db)

  return w,b


In [7]:
x_train = x_train.astype(np.float64)
x_train,x_std,x_mean = z_score(x_train)

np.random.seed(2147483647)
w = np.random.randn(x_train.shape[1],1)
b = np.random.randn(1)

old_cost = 0

while abs(old_cost - cost(x_train,y_train,w,b))>0.00001:
  old_cost = cost(x_train,y_train,w,b)
  w,b = gradient_descent(x_train,y_train,w,b)

  print(w)
  print(b)

x_predict = pd.read_excel('Test data.xlsx').iloc[:,:8].to_numpy()
x_predict = feature_changing(x_predict)
x_predict = (x_predict - x_mean)/x_std
ans = pd.read_excel('Test data.xlsx').iloc[:,8].to_numpy()


y_predict = np.dot(x_predict,w) + b
print(x_predict[0])
print(ans)
print(y_predict)

accuracy = 0
for dim in range(len(ans)):
  if abs(y_predict[dim]-ans[dim])<0.5: # do not change the tolerance as you'll be checked on +- 0.5 error only
    accuracy += 1
print(accuracy)
accuracy = round(accuracy*100/200.0,2)
ok = 'Congratulations' if accuracy>95 else 'Optimization required'
print(f"{ok}, your accuracy is {accuracy}%")


C:\Users\shree\AppData\Local\Temp\ipykernel_129568\3330750444.py:19: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  dj_dw[j] += error*x_train[i,j]


[[ 1.53319883]
 [-1.06734342]
 [ 1.32371466]
 [ 0.77706077]
 [-1.17118752]
 [-0.2147765 ]
 [-1.04252005]
 [ 0.25083895]]
[1.8358617]
[[ 1.44073539]
 [-1.02784441]
 [ 1.25636455]
 [ 0.86276132]
 [-1.16916191]
 [-0.25313301]
 [-1.0072284 ]
 [ 0.4092349 ]]
[3.87949555]
[[ 1.35119502]
 [-0.98977284]
 [ 1.19105282]
 [ 0.94572882]
 [-1.1673589 ]
 [-0.29031512]
 [-0.97297737]
 [ 0.5627039 ]]
[5.86182038]
[[ 1.26448515]
 [-0.95307801]
 [ 1.12771787]
 [ 1.02605029]
 [-1.16576648]
 [-0.32635907]
 [-0.93973597]
 [ 0.71139946]]
[7.78467547]
[[ 1.18051612]
 [-0.917711  ]
 [ 1.06629994]
 [ 1.10381003]
 [-1.16437319]
 [-0.3613    ]
 [-0.90747417]
 [ 0.85547027]]
[9.64984491]
[[ 1.09920115]
 [-0.88362458]
 [ 1.00674106]
 [ 1.17908962]
 [-1.16316807]
 [-0.39517195]
 [-0.87616282]
 [ 0.9950604 ]]
[11.45905926]
[[ 1.02045619]
 [-0.8507732 ]
 [ 0.94898506]
 [ 1.25196806]
 [-1.16214067]
 [-0.42800789]
 [-0.84577365]
 [ 1.13030941]]
[13.21399718]
[[ 0.94419986]
 [-0.81911292]
 [ 0.8929774 ]
 [ 1.32252183]
 

In [13]:
x_predict = pd.read_excel('Test data.xlsx').iloc[:,:8].to_numpy()
x_predict = feature_changing(x_predict)
x_predict = (x_predict - x_mean)/x_std
ans = pd.read_excel('Test data.xlsx').iloc[:,8].to_numpy()
print(x_predict[0])

[1.0 0.9999999999999971 1.000000000000001 2.9999999999999654
 3.9999999999999734 5.000000000000015 17.99999999999967 114.00000000000065]
